### ISSUE TITLE
Can't use exec in ready state, and wrong prompt printed

### ISSUE THREAD

**Issue by ethanyu94** [mkozjak/node-telnet-client#34]
I am trying to use this to telnet into my own machine (OS X El Capitan). I can get it into the ready state, but the prompt is wrong (empty) and Exec does not call its callback. 

Here is my code: https://gist.github.com/ethanyu94/9490f864db272d8e1169

Here is the output:
```
$ node telnet.js
connection ready
prompt:

socket timeout!
connection closed
$
```
Here is a real telnet session:
```
$ telnet 127.0.0.1
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
login: ethanyu
Password:
Last login: Fri Dec 18 17:43:25 on ttys001
$ echo hello
hello
$
```
Can you tell me what I'm doing wrong? Thanks.

**Comment by mkozjak** [comment]
@ethanyu94: Can you try with prompt '$ ' and not '$', maybe?
Possibly I'm having a bug here, but let's see...

**Comment by ethanyu94** [comment]
If I try prompt '$ ' it doesn't even get into ready state, just times out.

**Comment by mkozjak** [comment]
Yeah, there are some problems with not properly escaping special characters. I'm working on a fix.
@stardast

**Comment by mkozjak** [comment]
@ethanyu94: This is now fixed in version 0.4.3. Thanks for reporting!

**Comment by ethanyu94** [comment]
Sorry, still not solved. Now it says my prompt is '$ ethanyu'.

**Comment by ethanyu94** [comment]
Alternatively, is there a prompt that you know should work? I can easily change my prompt to that and see how that goes.

**Comment by mkozjak** [comment]
Can you, please, do a tcpdump so i can see what happens? You can send it to my email.

**Comment by stardast** [comment]
I think there is a problem in the ethanyu94 code, not inside the module:
shellPrompt option should be something like: '\$ ' or /\$ /
you can try the matching of RegExp here:
https://regex101.com/

mkozjak, in my opinion, we should never do ".replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'))"

Cheers! :)

**Comment by mkozjak** [comment]
@stardast: I think we must do a .replace if the given prompt is not an instance of RegExp, already. That way the user can really match the '$' character, and not the end of the line. There's also a few other special character cases, and they are all covered with .replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')

Cheers!

**Comment by stardast** [comment]
What do you think of this?
https://github.com/stardast/node-telnet-client/commit/adfc2c7ad5ac9f373db8ec3f4080a017fe37aa03

:)

**Comment by mkozjak** [comment]
@stardast: Lookin' good! Although checkRegExp is not needed anymore. We can use ternary operators.
Pull Request? :)

**Comment by mkozjak** [comment]
@ethanyu94: You are now encouraged to try the latest version, 0.5.0. This should work as expected.

**Comment by ethanyu94** [comment]
Works now. Thanks!

**Comment by mkozjak** [comment]
Awesome! Closing the ticket.
